(config/load-config-file "dired-conf.el")
(config/load-config-file "gnus-conf.el")
(config/load-config-file "ibuffer-conf.el")
(config/load-config-file "ido-conf.el")
(config/load-config-file "image-conf.el")
