(add-hook 'asm-mode-hook 'helm-cscope-mode)
(add-hook 'c-mode-hook 'helm-cscope-mode)
(add-hook 'c++-mode-hook 'helm-cscope-mode)
(add-hook 'python-mode-hook 'helm-cscope-mode)
(add-hook 'dired-mode-hook 'helm-cscope-mode)
