(config/load-config-file "ispell-conf.el")
(config/load-config-file "flyspell-conf.el")
(config/load-config-file "org-conf.el")
(config/load-config-file "rst-conf.el")
(config/load-config-file "tex-conf.el")
