(config/load-config-file "auto-complete-conf.el")
(config/load-config-file "eshell-conf.el")
(config/load-config-file "magit-conf.el")
(config/load-config-file "rainbow-delimiters-mode-conf.el")
(config/load-config-file "xcscope-conf.el")
(config/load-config-file "yasnippet-conf.el")
